name: B7

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # its a static HTML file. no dependencies, testing, or bulding of webpage required
      - name: discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
           webhook: ${{ secrets.SECRET }}
           message: hello all, ${{ github.repository }} has been successfullly deployed.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET }}
          publish_dir: ./  # Publish the root directory where your HTML file is located
