name: MyWorkflow file 

on:
  pull_request:
  push:
    branches: [main]
jobs: 
  builds:
    runs-on: Ubuntu-20.04

    steps: 

    # this is where i install python
    - name: Installing python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: check version of python 
      run: 
         python --version 

    # installing dependencies if any
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install html5lib beautifulsoup4

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PRACSECRET }}
        publish_dir: ./ 
