name: Practical File 

on:
  pull_request:
  push:
    branches: [main]
jobs: 
  builds:
    runs-on: ubuntu-latest
    

    steps: 

     - name: greeting steps
       run:
        echo "Hi I am learning git"
           
     - name: Checkout my codes
       uses: actions/checkout@v4
     - name: print content 
       run: 
         ls 

    # this is where i install python
     - name: Installing python
       uses: actions/setup-python@v5
       with:
        python-version: '3.10'
     - name: check version of python 
       run: 
         python --version 

    # installing dependencies if any
     - name: install dependencies
       run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
        pip install pytest



          
     - name: Deploy to Github Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
        github_token: ${{ secrets.SECRET }}
        publish_dir: ./  
